version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:${version}
    labels:
      - 'custom.project=test'
      - 'custom.service=test'
    ports:
      - '${port}:80'
    volumes:
      - '${config}:/etc/nginx/nginx.conf:ro'
      - '${home}/conf.d:/etc/nginx/conf.d/'
      - '${home}/html:/usr/share/nginx/html/'
      - '${home}/logs:/var/log/nginx/'
    restart: on-failure
