version: '3'
services:
  kafka-zookeeper:
    container_name: kafka-zookeeper
    hostname: kafka-zookeeper
    image: confluentinc/cp-zookeeper:${version}
    labels:
      - 'custom.project=kafka'
      - 'custom.service=zookeeper'
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - type: volume
        source: data
        target: /var/lib/zookeeper/data
        consistency: delegated
      - '${home}/logs:/var/lib/zookeeper/log'
      - '${home}/backups:/var/backups'
    restart: on-failure

  kafka:
    container_name: kafka
    hostname: ${host}
    image: confluentinc/cp-kafka:${version}
    labels:
      - 'custom.project=kafka'
      - 'custom.service=broker'
    depends_on:
      - kafka-zookeeper
    links:
      - kafka-zookeeper
    ports:
      - '29092:29092'
      - '${port}:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'kafka-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - '${home}/kafka/data:/var/lib/kafka/data'
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

volumes:
  data:

  # kafka-schema-registry:
  #   container_name: kafka-schema-registry
  #   hostname: kafka-schema-registry
  #   image: confluentinc/cp-schema-registry
  #   labels:
  #     - "custom.project=kafka"
  #     - "custom.service=schema-registry"
  #   depends_on:
  #     - kafka-zookeeper
  #     - kafka
  #   ports:
  #     - "8085:8081"
  #   environment:
  #     SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
  #     SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'kafka-zookeeper:2181'
# Disabled because of huge resource consumption. To use it please
# increase docker memory up to 8GB at Settings/Preferences -> Resources

#  kafka-connect:
#    container_name: kafka-connect
#    hostname: kafka-connect
#    image: confluentinc/cp-server-connect:latest
#    depends_on:
#      - kafka-zookeeper
#      - kafka
#      - kafka-schema-registry
#    ports:
#      - "8083:8083"
#    volumes:
#      - ./data/mi4:/tmp/
#    environment:
#      CONNECT_BOOTSTRAP_SERVERS: 'kafka:9092'
#      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
#      CONNECT_REST_PORT: 8083
#      CONNECT_GROUP_ID: compose-connect-group
#      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
#      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
#      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
#      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
#      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
#      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
#      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
#      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081
#      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
#      CONNECT_ZOOKEEPER_CONNECT: 'kafka-zookeeper:2181'
#      # CLASSPATH required due to CC-2422
#      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-5.4.0.jar
#      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
#      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
#      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
#      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
#
#  ksql-server:
#    container_name: ksql-server
#    hostname: ksql-server
#    image: confluentinc/cp-ksql-server:latest
#    labels:
#      - "custom.project=kafka"
#      - "custom.service=ksql-server"
#    depends_on:
#      - kafka
#      - kafka-connect
#    ports:
#      - "8088:8088"
#    environment:
#      KSQL_CONFIG_DIR: "/etc/ksql"
#      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
#      KSQL_HOST_NAME: ksql-server
#      KSQL_LISTENERS: "http://0.0.0.0:8088"
#      KSQL_AUTO_OFFSET_RESET: "earliest"
#      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
#      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://kafka-schema-registry:8081"
#      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
#      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
#      KSQL_KSQL_CONNECT_URL: "http://kafka-connect:8083"
#
#  ksql-cli:
#    container_name: ksql-cli
#    hostname: ksql-cli
#    image: confluentinc/cp-ksql-cli:latest
#    depends_on:
#      - kafka
#      - kafka-connect
#      - ksql-server
#    entrypoint: /bin/sh
#    tty: true
#
#  kafka-cc:
#    container_name: kafka-cc
#    hostname: kafka-cc
#    image: confluentinc/cp-enterprise-control-center:latest
#    depends_on:
#      - kafka-zookeeper
#      - kafka
#      - kafka-schema-registry
#      - kafka-connect
#      - ksql-server
#    ports:
#      - 9021:9021
#    environment:
#      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
#      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'kafka-zookeeper:2181'
#      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
#      CONTROL_CENTER_KSQL_MICROSERVICES_URL: "http://ksql-server:8088"
#      CONTROL_CENTER_KSQL_MICROSERVICES_ADVERTISED_URL: "http://localhost:8088"
#      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://kafka-schema-registry:8081"
#      CONTROL_CENTER_REPLICATION_FACTOR: 1
#      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
#      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
#      CONTROL_CENTER_DEPRECATED_VIEWS_ENABLE: "true"
#      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
#      PORT: 9021
