services:
  kafka:
    container_name: kafka
    hostname: ${host}
    image: confluentinc/cp-kafka:${version}
    labels:
      - 'custom.project=kafka'
      - 'custom.service=kafka'
    ports:
      - '29092:29092'
      - '${port}:9092'
    environment:
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_BROKER_ID: 1
      KAFKA_SESSION_TIMEOUT: 5000
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - type: volume
        source: kafka-data
        target: /var/lib/kafka/data
        consistency: delegated
      - /var/run/docker.sock:/var/run/docker.sock:delegated
    restart: on-failure
    user: root

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    hostname: kafka-ui
    container_name: kafka-ui
    labels:
      - 'custom.project=kafka'
      - 'custom.service=ui'
    links:
      - kafka
    depends_on:
      - kafka
    ports:
      - '${uiport}:8080'
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: localhost
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    volumes:
      - '${home}/kafkaui:/etc/kafkaui:delegated'
    restart: on-failure
    user: root

volumes:
  kafka-data:
  logs:
