version: '3.9'
services:
  dynamodb:
    container_name: dynamodb
    hostname: ${host}
    image: amazon/dynamodb-local:${version}
    labels:
      - 'custom.project=dynamodb'
      - 'custom.service=dynamodb'
    ports:
      - '${port}:8000'
    volumes:
      - type: volume
        source: data
        target: /home/dynamodblocal/data
        consistency: delegated
    healthcheck:
      test: >
        curl http://localhost:8000
      interval: 10s
      start_period: 30s
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    restart: on-failure

volumes:
  data:
