version: '3.9'
services:
  neo4j:
    container_name: neo4j
    hostname: ${host}
    image: neo4j:${version}
    labels:
      - 'custom.project=neo4j'
      - 'custom.service=neo4j'
    ports:
      - '${port}:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - type: volume
        source: data
        target: /var/lib/neo4j/data
        consistency: delegated
      - '${home}/backups:/var/backups'
      - '${home}/import:/var/lib/neo4j/import'
      - '${home}/plugins:/var/lib/neo4j/plugins'
      - '${home}/logs:/logs'
    environment:
      NEO4J_AUTH: none
    restart: on-failure

volumes:
  data:
