services:
  redis:
    container_name: redis
    hostname: ${host}
    image: redislabs/redisearch:${version}
    labels:
      - 'custom.project=redis'
      - 'custom.service=redis'
    ports:
      - '${port}:6379'
    volumes:
      - type: volume
        source: data
        target: /data
        consistency: delegated
      - '${home}/logs:/var/log'
      - '${home}/backups:/var/backups'
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      start_period: 30s
      interval: 10s
      timeout: 3s
      retries: 3
    restart: on-failure
    user: root

  redis-ui:
    container_name: redis-ui
    hostname: redis-ui
    image: rediscommander/redis-commander:latest
    labels:
      - 'custom.project=redis'
      - 'custom.service=ui'
    depends_on:
      - redis
    links:
      - redis
    ports:
      - '${uiport}:8081'
    environment:
      - REDIS_HOSTS=local:${host}:${port}
      - PORT=8081
    healthcheck:
      test: ['CMD', 'wget', '-q', '--output-document', '-', 'localhost:8081']
      start_period: 30s
      interval: 10s
      timeout: 3s
      retries: 3
    restart: on-failure

volumes:
  data:

  # redis-bull:
  #   container_name: redis-bull
  #   hostname: redis-bull
  #   image: deadly0/bull-board
  #   labels:
  #     - "custom.project=redis"
  #     - "custom.service=bull"
  #   depends_on:
  #     - redis
  #   links:
  #     - redis
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=
  #     - BULL_PREFIX=bull
  #   ports:
  #     - "3000:3000"
  #   restart: no
