version: '3.9'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: ${host}
    image: rabbitmq:${version}
    labels:
      - 'custom.project=rabbitmq'
      - 'custom.service=rabbitmq'
    ports:
      - '${port}:5672'
      - '${mport}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: ${host}
    volumes:
      - type: volume
        source: data
        target: /var/lib/rabbitmq
        consistency: delegated
      - '${home}/backups:/var/backups'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 30s
      interval: 10s
      timeout: 3s
      retries: 3
    restart: on-failure

volumes:
  data:
