version: '3.9'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: ${host}
    image: rabbitmq:${version}
    labels:
      - 'custom.project=rabbitmq'
      - 'custom.service=rabbitmq'
    ports:
      - '${port}:5672'
      - '${mport}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: ${host}
    volumes:
      - '${home}/database:/var/lib/rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
